=== marcelltisza/NLVHSR_XMLGyak/XMLTaskNLVHSR/XMLNLVHSR.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="adatbazis">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="rendeles" type="rendelesTipus" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="konyvRendeles" type="konyvRendelesTipus" maxOccurs="unbounded"/>
				<xs:element name="vevo" type="vevoTipus" maxOccurs="unbounded"/>
				<xs:element name="torzsKartya" type="torzsKartyaTipus" maxOccurs="unbounded"/>
				<xs:element name="konyv" type="konyvTipus" maxOccurs="unbounded"/>
				<xs:element name="kiado" type="kiadoTipus" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="vevoKulcs">
			<xs:selector xpath="vevo"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:key name="torzsKartyaKulcs">
			<xs:selector xpath="torzsKartya"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:key name="konyvKulcs">
			<xs:selector xpath="konyv"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:key name="kiadoKulcs">
			<xs:selector xpath="kiado"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:key name="rendelesKulcs">
			<xs:selector xpath="rendeles"/>
			<xs:field xpath="@id"/>
		</xs:key>
		<xs:keyref name="vevo-torzsKartya" refer="torzsKartyaKulcs">
			<xs:selector xpath="vevo/torzsKartyaID"/>
            <xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="rendeles-vevo" refer="vevoKulcs">
			<xs:selector xpath="rendeles/vevoID"/>
            <xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="konyvRendeles-konyv" refer="konyvKulcs">
			<xs:selector xpath="konyvRendeles/konyvID"/>
            <xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="konyv-kiado" refer="kiadoKulcs">
			<xs:selector xpath="konyv/kiadoID"/>
            <xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="konyvRendeles-rendeles" refer="rendelesKulcs">
			<xs:selector xpath="konyvRendeles/rendelesID"/>
            <xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
	
	<xs:complexType name="vevoTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="lakcim" type="xs:string"/>
			<xs:element name="kor" type="xs:unsignedInt"/>
			<xs:element name="torzsKartyaID" type="xs:string"/>
			<xs:element name="regisztralt" type="xs:date"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="torzsKartyaTipus">
		<xs:sequence>
			<xs:element name="pontok" type="xs:string"/>
			<xs:element name="szintNev" type="xs:string"/>
			<xs:element name="szintErtek" type="xs:unsignedInt"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="konyvTipus">
		<xs:sequence>
			<xs:element name="szerzo" type="xs:string" maxOccurs="unbounded"/>
			<xs:element name="cim" type="xs:string"/>
			<xs:element name="ar" type="xs:int"/>
			<xs:element name="kotes" type="kotesTipus"/>
			<xs:element name="kiadoID" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	
	<xs:simpleType name="kotesTipus">
		<xs:restriction base="xs:string">
			<xs:enumeration value="kemeny"/>
			<xs:enumeration value="puha"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="kiadoTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="szekhely" type="xs:string"/>
			<xs:element name="alapitasEve" type="xs:unsignedInt"/>
			<xs:element name="elerhetoseg" type="elerhetosegTipus"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="elerhetosegTipus">
		<xs:sequence>
			<xs:element name="telefon" type="telefonTipus" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="email" type="emailTipus" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="emailTipus">
		<xs:restriction base="xs:string">
			<xs:pattern value="[\w.]+@\w+\.\w+"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="telefonTipus">
		<xs:restriction base="xs:string">
			<xs:pattern value="\+36-\d{1,2}/\d{3}-\d{4}"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="rendelesTipus">
		<xs:sequence>
			<xs:element name="datum" type="xs:date"/>
			<xs:element name="fizetendo" type="xs:unsignedInt"/>
			<xs:element name="vevoID" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="konyvRendelesTipus">
		<xs:sequence>
			<xs:element name="rendelesID" type="xs:string"/>
			<xs:element name="konyvID" type="xs:string"/>
			<xs:element name="darab" type="xs:unsignedInt"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
</xs:schema>

=== marcelltisza/NLVHSR_XMLGyak/XMLTaskNLVHSR/DOMParseNLVHSR/XMLNLVHSR2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<adatbazis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLNLVHSR.xsd">
    
    <!-- RENDELÉSEK -->
        
    <rendeles id="r1">
                
        <datum>2021-10-26</datum>
                
        <fizetendo>2500</fizetendo>
                
        <vevoID>v1</vevoID>
            
    </rendeles>
        
    <rendeles id="r2">
                
        <datum>2021-10-30</datum>
                
        <fizetendo>3200</fizetendo>
                
        <vevoID>v2</vevoID>
            
    </rendeles>
          
    
    <rendeles id="r3">
            
        
        <datum>2021-11-02</datum>
            
        
        <fizetendo>1500</fizetendo>
          
        
        <vevoID>v1</vevoID>
            
    </rendeles>
                		 

    <!-- KÖNYV RENDELÉSEK -->
            	   
    
    <konyvRendeles id="kr1">
                       		      
        
        <rendelesID>r1</rendelesID>
                       		       
        
        <konyvID>k1</konyvID>
                        		       
        
        <darab>1</darab>
                       	   
    
    </konyvRendeles>
            	   
    
    <konyvRendeles id="kr2">
                        		       
        
        <rendelesID>r1</rendelesID>
                       		       
        
        <konyvID>k2</konyvID>
                       		        
        
        <darab>2</darab>
                        	    
    
    </konyvRendeles>
            		   
    
    <konyvRendeles id="kr3">
                       		       
        
        <rendelesID>r2</rendelesID>
                        		        
        
        <konyvID>k1</konyvID>
                        		        
        
        <darab>1</darab>
                           
    
    </konyvRendeles>
            	   
    
    <konyvRendeles id="kr4">
                        		       
        
        <rendelesID>r2</rendelesID>
                        		        
        
        <konyvID>k2</konyvID>
                        		        
        
        <darab>1</darab>
                       	  
    
    </konyvRendeles>
            	    
    
    <konyvRendeles id="kr5">
                       		       
        
        <rendelesID>r2</rendelesID>
                       		       
        
        <konyvID>k3</konyvID>
                        		        
        
        <darab>1</darab>
                        	   
    
    </konyvRendeles>
      
          		   
    
    <konyvRendeles id="kr6">
                        		       
        
        <rendelesID>r3</rendelesID>
                       		       
        
        <konyvID>k3</konyvID>
                       		       
        
        <darab>1</darab>
            
    </konyvRendeles>
      

    <!-- VEVŐK -->
               
    
    <vevo id="v1">
                       	       
        
        <nev>Olajos Lajos</nev>
                       	      
        
        <lakcim>1077 Budapest, Wesselényi u. 55</lakcim>
                        	       
        
        <kor>19</kor>
                       
        
        <torzsKartyaID>tk1</torzsKartyaID>
                
        
        <regisztralt>2000-01-01</regisztralt>
           
    
    </vevo>
     
      
    
    <vevo id="v2">
                       	       
        
        <nev>Varga Katalin</nev>
                       	       
        
        <lakcim>3530 Miskolc, Rácz György u. 8</lakcim>
                       	       
        
        <kor>28</kor>
                        		
        
        <torzsKartyaID>tk2</torzsKartyaID>
                
        
        <regisztralt>2012-10-12</regisztralt>
            
    </vevo>
            	

    <!-- TÖRZSKÁRTYÁK -->
    	
    <torzsKartya id="tk1">
        		
        <pontok>10</pontok>
        		
        <szintNev>Normal</szintNev>
        		
        <szintErtek>1</szintErtek>
        	
    </torzsKartya>
    	
	
    <torzsKartya id="tk2">
        		
        <pontok>3</pontok>
        		
        <szintNev>Szuper</szintNev>
        		
        <szintErtek>3</szintErtek>
        	
    </torzsKartya>
        

    <!-- KÖNYVEK -->
        
    <konyv id="k1">
                
        <szerzo>Szilasi László</szerzo>
                
        <cim>Tavaszi hadjárat</cim>
                
        <ar>5000</ar>
                
        <kotes>kemeny</kotes>
                
        <kiadoID>kia1</kiadoID>
            
    </konyv>
        
    <konyv id="k2">
                
        <szerzo>Győrffy Ákos</szerzo>
                
        <cim>A távolodásban</cim>
                
        <ar>500</ar>
                
        <kotes>puha</kotes>
                
        <kiadoID>kia1</kiadoID>
            
    </konyv>
        
    <konyv id="k3">
                
        <szerzo>Andrew S. Tanenbaum</szerzo>
                
        <szerzo>David J. Wetherall</szerzo>
                
        <cim>Számítógép-hálózatok</cim>
                
        <ar>5000</ar>
                
        <kotes>kemeny</kotes>
                
        <kiadoID>kia1</kiadoID>
            
    </konyv>
    
    <!-- KIADÓK -->
        
    <kiado id="kia1">
                
        <nev>Magvető Könyvkiadó</nev>
                
        <szekhely>Budapest</szekhely>
                
        <alapitasEve>1955</alapitasEve>
                
        <elerhetoseg>
                        
            <telefon>+36-1/323-3981</telefon>
                        
            <telefon>+36-1/235-5032</telefon>
                        
            <email>magveto.kiado@lira.hu</email>
                    
            <email>valami@gmail.com</email>
        </elerhetoseg>
            
    </kiado>
        
    <kiado id="kia2">
                
        <nev>Panem</nev>
                
        <szekhely>Budapest</szekhely>
                
        <alapitasEve>1972</alapitasEve>
                
        <elerhetoseg>
                        
            <telefon>+36-1/460-0272</telefon>
                        
            <email>webbolt@panem.hu</email>
                    
        </elerhetoseg>
            
    </kiado>
            	

</adatbazis>
