=== marcelltisza/NLVHSR_XMLGyak/NLVHSR_1013/TM_konyv1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="konyvek">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="konyv" type="konyvTipus" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="konyvTipus">
		<xs:sequence>
			<xs:element name="cim" type="xs:string"/>
			<xs:element name="szerzo" type="xs:string"/>
			<xs:element name="szereplo" type="szereploTipus" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="isbn" type="xs:ID" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="szereploTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="baratja" type="xs:string"/>
			<xs:element name="szuletett" type="xs:date"/>
			<xs:element name="jellemzes" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
</xs:schema>

=== marcelltisza/NLVHSR_XMLGyak/NLVHSR_1013/TM_konyv1.xml
<?xml version="1.0" encoding="UTF-8"?>

<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  	 xsi:noNamespaceSchemaLocation="TM_konyv1.xsd">
	<konyv isbn="adssad">
		<cim>cim1</cim>
		<szerzo>szerzo1</szerzo>
		<szereplo id="s1">
			<nev>Adam</nev>
			<baratja>Kati</baratja>
			<szuletett>1990-12-12</szuletett>
			<jellemzes>jellemzok</jellemzes>
		</szereplo>
		<szereplo id="s2">
			<nev>Kati</nev>
			<baratja>Adam</baratja>
			<szuletett>1987-10-01</szuletett>
			<jellemzes>jellemzok</jellemzes>
		</szereplo>
	</konyv>
</konyvek>
