=== marcelltisza/NLVHSR_XMLGyak/NLVHSR_0928/TM_konyv.dtd
<!ELEMENT konyvek (konyv*)>
<!ELEMENT konyv (cim,kiadasev,kiado,szerzo+, absztrakt?)>
<!ATTLIST konyv id ID #REQUIRED>
<!ELEMENT cim (#PCDATA)>
<!ELEMENT kiadasev (#PCDATA)>
<!ELEMENT kiado (#PCDATA)>
<!ELEMENT szerzo (#PCDATA)>
<!ELEMENT absztrakt (#PCDATA)>

=== marcelltisza/NLVHSR_XMLGyak/NLVHSR_0928/TM_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE konyv SYSTEM "TM_konyv.dtd">

<konyvek>
	<konyv id="a1">
		<cim>cim</cim>
		<kiadasev>ev</kiadasev>
		<kiado>kiado</kiado>
		<szerzo>szerzo1</szerzo>	
	</konyv>
	<konyv id="s2">
		<cim>cim</cim>
		<kiadasev>ev</kiadasev>
		<kiado>kiado</kiado>
		<szerzo>szerzo1</szerzo>	
	</konyv>
	<konyv id="c3">
		<cim>cim</cim>
		<kiadasev>ev</kiadasev>
		<kiado>kiado</kiado>
		<szerzo>szerzo1</szerzo>	
	</konyv>
</konyvek>
