=== marcelltisza/NLVHSR_XMLGyak/NLVHSR_1006/TM_konyv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
		
<element name="konyvek">
	<complexType>
		<sequence>
			<element name="konyv" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="cim" type="string" />
						<element name="kiadasev" type="unsignedShort" />
						<element name="kiado" type="string" />
						<element name="szerzo" type="string" />
						<element name="absztrakt" type="string" minOccurs="0" />
					</sequence>
					<attribute name="id" type="string" use="required"/>
				</complexType>
			</element>
		</sequence>
	</complexType>
</element>

</schema>

=== marcelltisza/NLVHSR_XMLGyak/NLVHSR_1006/TM_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>

<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TM_konyv.xsd">
	<konyv id="a1">
		<cim>cim</cim>
		<kiadasev>2000</kiadasev>
		<kiado>kiado</kiado>
		<szerzo>szerzo1</szerzo>	
	</konyv>
	<konyv id="s2">
		<cim>cim</cim>
		<kiadasev>2000</kiadasev>
		<kiado>kiado</kiado>
		<szerzo>szerzo1</szerzo>
	</konyv>
	<konyv id="c3">
		<cim>cim</cim>
		<kiadasev>2000</kiadasev>
		<kiado>kiado</kiado>
		<szerzo>szerzo1</szerzo>	
	</konyv>
</konyvek>
